### ISSUE TITLE
Feedback on use cases

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor-configure#1]
I'm looking to map all the different use cases Capacitor developers have when looking to a tool like this. I want to make sure this tool can cater to those needs. My goal is you should never need to write or ship a custom script to configure your app, as that adds big maintenance and developer experience overhead.

Please share your use cases in this issue, thanks!

**Comment by alexcroox** [comment]
I have 2 white-labelled apps and 2 environments: production/development.

I currently have custom scripts to handle the automatic switching at build or local dev time of the following;

- capacitor-project.config.json
- replacement of bundle identifiers in all the various ios/andriod native files
- use `cordova-res` to switch out all the app icons and splash screens
- switch out fastlane configs for appstore screenshots and store description/submission automation

I've x'd out sensitive info and zipped up these scripts so you can get a better idea of how I automate these 8 different apps. The second-brand folder has been emptied because I didn't have time to erase all sensitive info from that folder too but it's format is the same as the "farmto" folder.

https://p193.p3.n0.cdn.getcloudapp.com/items/v1ujvdQd/1d58cae3-a9fa-43a3-a7c4-effde271ca4f.zip

**Comment by jmellicker** [comment]
@mlynch FYI, here's a script an (ex) team member wrote a while back to perform some of the same file updates for a white-label app:

[https://gist.github.com/jmellicker/ad4aaff5c68b9220aa5b4f628086bd89](https://gist.github.com/jmellicker/ad4aaff5c68b9220aa5b4f628086bd89)

Your utility probably handles these updates better, just posting if you're curious how some people have solved this problem before.

Also FYI, I've always preferred `.json` over `.yaml` for config files 😎, — easier to update programmatically and extend for other purposes. For our use case we would want all our config in one file for each brand, combining the values `capacitor-configure` works with, along with other brand-specific values (e.g., brand colors, Fastlane variables, Firebase App Distribution ids, etc.).

**Comment by mlynch** [comment]
Thanks @jmellicker will take a look, that should be very helpful!

re: json vs yaml, since yaml is a superset of json it would be trivial to support json. In fact it might Just Work right now if you try it 😁 I have really liked how yaml feels for this, especially since many of the config options take raw source which can be really tricky in json. But if it Just Works I would be happy to recommend it for people who prefer that!

**Comment by mlynch** [comment]
Closing as I feel good about where things are at. More feedback on how you'd like to use this tool very welcome, just reply in this issue thread.
