### ISSUE TITLE
How to use the capacitor project

### ISSUE THREAD

**Issue by marioshtika** [ionic-team/capacitor-configure#12]
Hello to everyone and thank you for this tool.

I read the blog post [Automated Capacitor Project Configuration with Capacitor Configure](https://ionicframework.com/blog/automated-capacitor-project-configuration-with-capacitor-configure/), I also read the documentation on this repository and I didn't understand how and when should I run the project configuration.

Should I use the `capacitor.config.ts` or should I create a new file?
How should I run it?
Will it run every time I use the capacitor cli (example adding platform)?
Should I run the new `.ts` file using node?
When I do that it is showing the below error:
```
SyntaxError: Cannot use import statement outside a module
```

I am really looking forward using this tool.
Any help would be appreciated

**Comment by sandor-biro** [comment]
Hi @mlynch & everyone else here!

I've just had the opportunity to check if we can integrate this tool at our company.

Until now I 100% agree with @marioshtika. Some working examples and/or more info about how to get started with this promising tool would be highly appreciated.

We <3 to early adopt new & cool tools and we would be happy to simplify our processes by implementing this one for our apps and, of course, to contribute to it as much as we can.

Congrats & greetings & many thanks in advance!

**Comment by mlynch** [comment]
Good question. I've left it open ended because I don't really know the best way to use it just yet. I wanted to be careful about recommending users put calls in `capacitor.config.ts` because it'll be executed occasionally when using the Capacitor CLI in a way that could be unexpected, but you can certainly put it in there if you like.

Otherwise, use it like any other JS library and write a script that imports it. You don't even need to use typescript. For example, a simple node script that imports from `@capacitor/project` would suffice. I'm not sure about the error you're getting, but that wouldn't likely be related to this library (rather your typescript config).

Of course the configuration tool is a different situation and definitely needs a lot more documentation which is forthcoming.

Does that help at all?

**Comment by marioshtika** [comment]
Thank you @mlynch,

your answer helped me a lot, at least to understand how to start and what to expect from it.

I think it is going to be a great tool, at least to me, which I am trying to do some difficulty/weird 😄  configurations.

Also I found yesterday that @saimon24 added a new youtube video on how to [How to AUTOMATICALLY configure your Capacitor project](https://www.youtube.com/watch?v=kYFZkmJ6rAc).

Thank you @saimon24 for that.

**Comment by mario-tessera** [comment]
Hello Max, 

with your instructions and from Simons tutorials I was able to configure both iOS and Android projects using both a `ts` file and a `yml` file.

You can close this issue if you want.

**Comment by marioshtika** [comment]
Hello Max,

with your instructions and from Simons tutorials I was able to configure both iOS and Android projects using both a `ts` file and a `yml` file.

You can close this issue if you want.
